import type { MediaRef } from '@sahoda/shared'

import { ZernioError, type ZernioClient } from './client'

/**
 * Get generated bytes onto a URL Instagram will actually fetch.
 *
 * ── WHY WE UPLOAD RATHER THAN HAND OVER OUR OWN URL ───────────────────────────
 * Doc 13 §9's ruling. Supabase signed URLs are not rejected by Zernio — the token
 * rides in the query string — the problem is EXPIRY, which is silent, time-dependent,
 * and lands at publish time when nobody is watching. A three-week-out post needs a
 * three-week token, so you take the privacy cost AND the expiry risk together.
 *
 * Uploading moves the failure to where a human is standing: if it fails while
 * scheduling, the user picks another image. If a URL expires at 9am Saturday, the
 * post silently does not go out and the customer believes it did.
 *
 * ── THE PRE-FLIGHT THAT NEARLY WASN'T ─────────────────────────────────────────
 * Doc 13 §9 requires a HEAD before publish asserting status AND Content-Type.
 * Written naively that pre-flight FAILS on Zernio's own CDN: media.zernio.com sits
 * behind Cloudflare's browser-integrity check, and a default (non-browser)
 * User-Agent gets 403 with `error code: 1010`. Verified 2026-07-31 — the same URL
 * answered 200 image/jpeg to a browser UA and to facebookexternalhit, which is what
 * Meta actually sends. The client sends BROWSER_UA for exactly this reason.
 */

/** Instagram accepts these and nothing else (doc 13 §6). */
const INSTAGRAM_MIME = new Set(['image/jpeg', 'image/png'])

export interface UploadedMedia extends MediaRef {
  /** Zernio's storage key, kept for a future retention/cleanup job. */
  key: string
}

export interface UploadMediaInput {
  bytes: Uint8Array
  mime: string
  filename: string
  altText?: string
}

/**
 * Presign → PUT → verify → a URL safe to hand to Instagram.
 *
 * Throws rather than returning a half-result: a caller holding a URL from this
 * function may assume it serves real image bytes with no redirect.
 */
export async function uploadMediaToZernio(
  client: ZernioClient,
  input: UploadMediaInput,
): Promise<UploadedMedia> {
  if (!INSTAGRAM_MIME.has(input.mime)) {
    // Rejected HERE as well as at compose time. The Constraint Engine catches the
    // user's file; this catches anything we generate ourselves — the image model
    // returning WebP, say — which never passes through the editor's validation.
    throw new ZernioError({
      message: `Instagram accepts JPEG and PNG only; got ${input.mime}.`,
      status: 0,
      code: 'MEDIA_TYPE',
      type: 'client_error',
      rateLimit: { limit: null, remaining: null, reset: null },
    })
  }

  const presigned = await client.presignMedia({
    filename: input.filename,
    contentType: input.mime,
    size: input.bytes.byteLength,
  })

  await client.uploadMedia(presigned.uploadUrl, input.bytes, input.mime)

  // Three assertions, separately — status, an image content-type, and no redirect.
  // A 302 is a hard failure for Zernio media (Drive/Dropbox/OneDrive serve an HTML
  // interstitial), and a status-only check waves it straight through.
  const head = await client.headMedia(presigned.publicUrl)
  const problems: string[] = []
  if (head.status !== 200) problems.push(`status ${head.status}`)
  if (!head.contentType.toLowerCase().startsWith('image/')) {
    problems.push(`content-type ${head.contentType || '<none>'}`)
  }
  if (head.redirected) problems.push('the URL redirects')

  if (problems.length > 0) {
    throw new ZernioError({
      message: `Uploaded media is not publicly fetchable (${problems.join(', ')}).`,
      status: head.status,
      code: 'MEDIA_NOT_FETCHABLE',
      type: 'media_error',
      rateLimit: { limit: null, remaining: null, reset: null },
    })
  }

  return {
    url: presigned.publicUrl,
    mime: input.mime,
    bytes: input.bytes.byteLength,
    key: presigned.key,
    ...(input.altText ? { altText: input.altText } : {}),
  }
}

/**
 * Decode an image the model returned as base64.
 *
 * OpenRouter's image responses carry a data URL or bare base64; both arrive here.
 * The mime is read from the data URL when present because the caller usually asked
 * for one format and cannot assume it got it — that assumption is defect 4.
 */
export function decodeBase64Image(raw: string): { bytes: Uint8Array; mime: string } {
  const dataUrl = /^data:([a-z0-9.+/-]+);base64,(.*)$/is.exec(raw.trim())
  const mime = dataUrl?.[1]?.toLowerCase() ?? 'image/png'
  const payload = dataUrl?.[2] ?? raw
  const bytes = Uint8Array.from(Buffer.from(payload, 'base64'))
  return { bytes, mime: sniffMime(bytes) ?? mime }
}

/**
 * Trust the bytes over the label. A generator that says PNG and returns WebP is
 * exactly how a non-JPEG/PNG file reaches Instagram and fails at publish time.
 */
export function sniffMime(bytes: Uint8Array): string | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return 'image/jpeg'
  }
  if (
    bytes.length >= 8 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47
  ) {
    return 'image/png'
  }
  // RIFF....WEBP — named so the error can say what it actually got.
  if (
    bytes.length >= 12 &&
    bytes[0] === 0x52 &&
    bytes[1] === 0x49 &&
    bytes[2] === 0x46 &&
    bytes[3] === 0x46 &&
    bytes[8] === 0x57 &&
    bytes[9] === 0x45 &&
    bytes[10] === 0x42 &&
    bytes[11] === 0x50
  ) {
    return 'image/webp'
  }
  return null
}
