#!/usr/bin/env node
/**
 * The lint leg of the gate, which until now could not fail.
 *
 * MEASURED before this file existed: `lint` was the literal string `exit 0` in
 * all nine packages and there was no eslint config anywhere in the repo. The
 * gate ran a leg that structurally could not go red, which is worse than having
 * no leg — a green `lint` was being read as evidence.
 *
 * These are the three rules docs/26 makes load-bearing and that nothing else
 * checks. They are deliberately NOT eslint rules: eslint parses TypeScript, and
 * two of the three are about CSS class strings and rendered markup, which is
 * text. A regex over text that says what it means beats an AST rule that has to
 * reconstruct the string anyway.
 *
 *   1 · no raw hex            docs/26 §11 — "Do not write a raw hex. Anywhere."
 *   2 · no hardcoded spacing  docs/26 §6  — spacing is --space-N, never a literal
 *   3 · no disabled button    docs/26 §10.2 — coming-soon is a <span>, never
 *                             <button disabled>, which a screen reader still
 *                             announces as an action the user can take
 *
 * Scope is apps/web/src. Two allowlists, both narrow and both justified below.
 *
 * Usage:  node scripts/design/design-lint.mjs [--report]
 *         --report prints every violation instead of the first few.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = new URL('../..', import.meta.url).pathname
const SCOPE = join(ROOT, 'apps/web/src')
const REPORT = process.argv.includes('--report')

/* ── ALLOWLIST 1 · files that are ALLOWED raw hex ──────────────────────────────
   tokens.css is the source of truth for values and is outside SCOPE anyway; its
   generated inline copy is inside SCOPE and must not be hand-edited. The design
   tooling reasons ABOUT hex, so it necessarily contains it. */
const HEX_EXEMPT_FILES = [
  'lib/sites/tokens-css-inline.ts', // generated by scripts/gen-tokens-inline.mjs
  'lib/design/own-medicine.test.ts', // grades tokens.css, so it quotes tokens.css
]

/* ── ALLOWLIST 2 · platform brand marks ───────────────────────────────────────
   docs/26 §1.6: "Platform marks (Instagram, LinkedIn, …) keep their own brand
   colours. That is identity, not UI chrome, and it is the only exception."
   Named as PATHS rather than as colour values, so the exception is visible in
   the file tree instead of hidden in a list of hexes. */
const BRAND_MARK_PATHS = [/components\/(connections|inbox|posts)\/.*(icon|mark|logo|glyph)/i]

const files = []
;(function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full)
    else if (/\.(tsx?|css)$/.test(entry)) files.push(full)
  }
})(SCOPE)

/** Comments are stripped everywhere: a rule that fires on its own documentation
 *  teaches the next session to delete the explanation, not to keep the rule. */
function stripComments(src) {
  return (
    src
      .replace(/\/\*[\s\S]*?\*\//g, '')
      // TRAILING line comments too, not just whole-line ones. brand-theme.ts
      // annotates each neutral with the token hex it mirrors — real
      // documentation that guard-neutrals.test.ts enforces — and a rule that
      // fired on it would be answered by deleting the annotation.
      // The `[^:]` guard keeps `https://` intact.
      .replace(/(^|[^:])\/\/.*$/gm, '$1')
  )
}

const violations = { hex: [], spacing: [], disabled: [] }

/** 3, 4, 6 or 8 digit hex, as a colour — not a hash-route or an id. */
const HEX = /#[0-9a-fA-F]{3,8}\b/g
/** Tailwind arbitrary SPACING: padding, margin, gap, space, inset — px literals. */
const SPACING =
  /\b(?:-?(?:p|m)[trblxy]?|gap(?:-[xy])?|space-[xy]|inset(?:-[xy])?)-\[[^\]]*\d(?:px|rem)[^\]]*\]/g

for (const file of files) {
  const rel = relative(SCOPE, file)
  const raw = readFileSync(file, 'utf8')
  const code = stripComments(raw)
  const lines = code.split('\n')

  const hexExempt = HEX_EXEMPT_FILES.includes(rel) || BRAND_MARK_PATHS.some((re) => re.test(rel))

  lines.forEach((line, i) => {
    if (!hexExempt) {
      for (const m of line.matchAll(HEX)) violations.hex.push({ rel, line: i + 1, text: m[0] })
    }
    for (const m of line.matchAll(SPACING)) {
      violations.spacing.push({ rel, line: i + 1, text: m[0] })
    }
  })

  /* Rule 3 · a <button> that is BOTH disabled and labelled coming-soon.
     Matched over the whole element rather than one line, because the attribute
     and the label are almost never on the same line in formatted JSX. */
  for (const m of code.matchAll(/<button\b[\s\S]{0,600}?<\/button>/g)) {
    const el = m[0]
    if (/\bdisabled\b/.test(el) && /coming\s*soon/i.test(el)) {
      violations.disabled.push({
        rel,
        line: code.slice(0, m.index).split('\n').length,
        text: 'disabled <button> labelled coming soon',
      })
    }
  }
}

/* ── THE SPACING RATCHET ──────────────────────────────────────────────────────
   MEASURED when this rule was written: 133 hardcoded spacing values across
   seven lanes' files. Two honest options and one dishonest one.

   Dishonest: drop the rule, or scope it to the files this lane happens to
   touch. Then the leg still cannot fail for anyone else, which is the exact
   defect being fixed.

   Rejected: fix all 133 now. Most sit in routes other lanes own — /approvals,
   /admin, /campaigns, /brain — and rewriting another lane's spacing to satisfy
   a rule they have not read is how a merge conflict becomes a regression.

   Chosen: a RATCHET, with the debt written down in `design-lint-baseline.json`
   rather than hidden in an ignore list. Per FILE counts, not per line: line
   numbers churn on every edit, so a line-keyed baseline goes stale immediately
   and stops being read. A file may never gain a violation, and every one it
   loses tightens the baseline permanently. The number is in the file, in git,
   and it only goes down.

   Regenerate with --update-baseline after REMOVING violations. It refuses to
   loosen: a file that gained violations is reported, never absorbed. */
const BASELINE_PATH = join(ROOT, 'scripts/design/design-lint-baseline.json')

function loadBaseline() {
  try {
    return JSON.parse(readFileSync(BASELINE_PATH, 'utf8')).spacing ?? {}
  } catch {
    return {}
  }
}

function countByFile(list) {
  const out = {}
  for (const v of list) out[v.rel] = (out[v.rel] ?? 0) + 1
  return out
}

let failed = 0

/* Rules 1 and 3 are at ZERO and are enforced strictly — no baseline, no grace.
   Measured at zero when written, so any violation is one this lane or a later
   one introduced. */
for (const [key, name, why] of [
  ['hex', 'raw hex colour', 'docs/26 §11 — tokens only'],
  ['disabled', 'disabled coming-soon button', 'docs/26 §10.2 — use a <span>'],
]) {
  const found = violations[key]
  if (found.length === 0) {
    console.log(`  ok    ${name}`)
    continue
  }
  failed += found.length
  console.log(`  FAIL  ${name} — ${found.length} (${why})`)
  for (const v of REPORT ? found : found.slice(0, 12)) {
    console.log(`          ${v.rel}:${v.line}  ${v.text}`)
  }
  if (!REPORT && found.length > 12) console.log(`          … ${found.length - 12} more (--report)`)
}

/* Rule 2 · ratcheted. */
const current = countByFile(violations.spacing)
const baseline = loadBaseline()

if (process.argv.includes('--update-baseline')) {
  const merged = {}
  for (const rel of Object.keys(current).sort()) merged[rel] = current[rel]
  writeFileSync(
    BASELINE_PATH,
    `${JSON.stringify({ _: 'docs/26 §6 debt register. Counts may only go DOWN — see design-lint.mjs.', total: violations.spacing.length, spacing: merged }, null, 2)}\n`,
  )
  console.log(`  baseline written — ${violations.spacing.length} hardcoded spacing values`)
} else {
  const regressed = []
  for (const [rel, n] of Object.entries(current)) {
    const allowed = baseline[rel] ?? 0
    if (n > allowed) regressed.push({ rel, n, allowed })
  }
  const improved = Object.entries(baseline).filter(([rel, n]) => (current[rel] ?? 0) < n)
  const total = violations.spacing.length
  const baseTotal = Object.values(baseline).reduce((a, b) => a + b, 0)

  if (regressed.length === 0) {
    console.log(`  ok    hardcoded spacing — ${total} known, none new (baseline ${baseTotal})`)
    if (improved.length > 0) {
      console.log(
        `        ${improved.length} file(s) improved — run --update-baseline to tighten it`,
      )
    }
  } else {
    failed += regressed.length
    console.log(`  FAIL  hardcoded spacing — NEW in ${regressed.length} file(s)`)
    console.log(`        docs/26 §6 — spacing is --space-N / the 4pt scale, never a px literal`)
    for (const r of regressed) {
      console.log(`          ${r.rel}  ${r.n} (baseline allows ${r.allowed})`)
      for (const v of violations.spacing.filter((v) => v.rel === r.rel)) {
        console.log(`            :${v.line}  ${v.text}`)
      }
    }
  }
}

console.log(`\n  ${files.length} files scanned in apps/web/src`)
process.exit(failed > 0 ? 1 : 0)
