#!/usr/bin/env node
/**
 * The lint leg of the gate, which until now could not fail.
 *
 * MEASURED before this file existed: `lint` was the literal string `exit 0` in
 * all nine packages and there was no eslint config anywhere in the repo. The
 * gate ran a leg that structurally could not go red, which is worse than having
 * no leg — a green `lint` was being read as evidence.
 *
 * These are the three rules docs/26 makes load-bearing and that nothing else
 * checks. They are deliberately NOT eslint rules: eslint parses TypeScript, and
 * two of the three are about CSS class strings and rendered markup, which is
 * text. A regex over text that says what it means beats an AST rule that has to
 * reconstruct the string anyway.
 *
 *   1 · no raw hex            docs/26 §11 — "Do not write a raw hex. Anywhere."
 *   2 · no hardcoded spacing  docs/26 §6  — spacing is --space-N, never a literal
 *   3 · no disabled button    docs/26 §10.2 — coming-soon is a <span>, never
 *                             <button disabled>, which a screen reader still
 *                             announces as an action the user can take
 *   4 · no dead breakpoint    globals.css does `--breakpoint-*: initial`, so
 *                             `sm:` `md:` `lg:` `xl:` `2xl:` DO NOT EXIST. A
 *                             class using one is silently never generated
 *
 * Scope is apps/web/src. Two allowlists, both narrow and both justified below.
 *
 * Usage:  node scripts/design/design-lint.mjs [--report]
 *         --report prints every violation instead of the first few.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = new URL('../..', import.meta.url).pathname
const SCOPE = join(ROOT, 'apps/web/src')
const REPORT = process.argv.includes('--report')

/* ── ALLOWLIST 1 · files that are ALLOWED raw hex ──────────────────────────────
   tokens.css is the source of truth for values and is outside SCOPE anyway; its
   generated inline copy is inside SCOPE and must not be hand-edited. The design
   tooling reasons ABOUT hex, so it necessarily contains it. */
const HEX_EXEMPT_FILES = [
  'lib/sites/tokens-css-inline.ts', // generated by scripts/gen-tokens-inline.mjs
  'lib/design/own-medicine.test.ts', // grades tokens.css, so it quotes tokens.css
  /* The onboarding swatch DEFAULTS. Same class as the two above: this file
     necessarily contains hex, because the values are `<input type="color">`
     data and the HTML spec requires that element's value be exactly `#rrggbb`
     — `var(--p)` in it is not a colour the control can show, it is an invalid
     value the browser silently replaces with black. They are DATA the user
     edits, not styling this file applies, and nothing in the file paints
     anything. The stylesheet beside it, `styles/onboarding.css`, carries zero
     raw hex and stays enforced. */
  'components/onboarding/stage/store.ts',
  /* The DPDP export's readable page. Same class again, and it is the strongest
     case in the list: this file does not style anything in this app. It
     GENERATES a standalone HTML document that lands in the customer's Downloads
     folder, has to open from a folder with no network in two years, and has no
     stylesheet to import — `var(--surface)` in it resolves to nothing at all.
     Values are the only thing that renders. It also cannot drift, because it is
     regenerated from scratch on every download rather than being a copy of
     anything. The app-facing half of this feature, `your-data-panel.tsx`, uses
     tokens and stays enforced. */
  'lib/privacy/readable.ts',
]

/* ── ALLOWLIST 2 · platform brand marks ───────────────────────────────────────
   docs/26 §1.6: "Platform marks (Instagram, LinkedIn, …) keep their own brand
   colours. That is identity, not UI chrome, and it is the only exception."
   Named as PATHS rather than as colour values, so the exception is visible in
   the file tree instead of hidden in a list of hexes. */
const BRAND_MARK_PATHS = [/components\/(connections|inbox|posts)\/.*(icon|mark|logo|glyph)/i]

const files = []
;(function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full)
    else if (/\.(tsx?|css)$/.test(entry)) files.push(full)
  }
})(SCOPE)

/** Comments are stripped everywhere: a rule that fires on its own documentation
 *  teaches the next session to delete the explanation, not to keep the rule. */
/**
 * Comments removed, LINE NUMBERS PRESERVED.
 *
 * The first version replaced a block comment with '', which deleted its
 * newlines — so every reported line number after the first comment in a file
 * was wrong, and this codebase has long header comments in almost every file.
 * A rule that points at the wrong line is worse than no rule: it sends the
 * reader to innocent code and teaches them the tool is noise. Each comment is
 * now replaced by the newlines it contained.
 *
 * TRAILING line comments go too, not just whole-line ones. brand-theme.ts
 * annotates each neutral with the token hex it mirrors — real documentation
 * that guard-neutrals.test.ts enforces — and a rule that fired on it would be
 * answered by deleting the annotation. The `[^:]` guard keeps `https://`.
 */
function stripComments(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
    .replace(/(^|[^:])\/\/.*$/gm, '$1')
}

const violations = { hex: [], spacing: [], disabled: [], breakpoint: [], typesize: [] }

/* ── RULE 4 · DEAD BREAKPOINT VARIANTS ────────────────────────────────────────
   `apps/web/src/app/globals.css` opens `@theme` with `--breakpoint-*: initial`,
   which REMOVES every stock Tailwind breakpoint, and then defines exactly two:
   `narrow` (700px) and `wide` (1180px). Anything written as `sm:` / `md:` /
   `lg:` / `xl:` / `2xl:` is therefore a variant Tailwind does not know, so the
   rule is never emitted and the base class wins at every width.

   PROVEN, not assumed: `sm:w-auto` appears 0 times in the compiled CSS while
   `max-narrow:` appears 48 times.

   This is not a style rule. `top-up-panel.tsx` carried `w-full sm:w-auto` on
   `Start checkout`, so the loudest object in the product — a brand-filled
   button, on the money screen — rendered as a ~1000px bar at 1440px. Someone
   wrote the fix; it simply never existed. Nothing could catch it: the class is
   spelled correctly, it type-checks, and it reads right in review.

   The allowed names are READ FROM globals.css rather than restated here, so
   adding a breakpoint cannot leave this rule stale. */
const GLOBALS = join(ROOT, 'apps/web/src/app/globals.css')
const DEFINED_BREAKPOINTS = new Set(
  [...readFileSync(GLOBALS, 'utf8').matchAll(/--breakpoint-([a-z0-9-]+)\s*:/g)]
    .map((m) => m[1])
    .filter((n) => n !== '*'),
)
/** Any `word:` variant that looks like a breakpoint but is not a defined one. */
/**
 * The trailing `[a-z0-9[-]` is load-bearing. A Tailwind variant is `sm:` glued
 * to the class it modifies (`sm:w-auto`); a TypeScript object KEY is `sm:`
 * followed by a space (`sm: 'h-7 px-[9px]'`). Without it this rule flagged
 * button.tsx's CVA size variants, which are not classes at all — a false
 * positive on the most-used primitive in the app, which is exactly how a new
 * rule gets switched off in its first week.
 */
const BREAKPOINT_LIKE = /(?:^|[\s"'`])(?:(max)-)?(sm|md|lg|xl|2xl):(?=[a-z0-9[-])/g

/* ── RULE 5 · HAND-WRITTEN FONT SIZES ─────────────────────────────────────────
   docs/26 §11 names this outright — "Do not hand-write a font shorthand or a
   pixel size" — and §5 ships the whole scale as `@utility type-*` in
   globals.css precisely "so components never hand-write a font shorthand".
   Nothing checked it.

   MEASURED when this rule was written: 847 hand-written sizes across 192 files,
   in EIGHTEEN distinct pixel values against a scale of eight steps, and 49
   distinct (size, weight) pairs. Eleven of those sizes — 10, 11.5, 12.5, 13.5,
   14, 16, 17, 18, 19, 25, 28 — are not on the scale at all, so they are not
   shortcuts for a step, they are invented steps.

   This is the mechanism docs/27 §4 diagnosed: the same question answered
   independently on every screen. It is also the one docs/28's four rules could
   not see, and the reason `text-[15px] font-semibold` drifted into being at
   every call site until `type-h3` was added to collect them.

   SIZE ONLY, deliberately. §5 forbids a font SHORTHAND — size, weight and
   leading welded together — and the scale's steps carry a default weight. A
   separate `font-semibold` beside `type-body` is a legal, single-purpose
   utility, so folding weight into this rule would flag correct code and get the
   rule switched off in its first week, which is how rule 4 nearly died. */
const FONT_SIZE = /\btext-\[\d+(?:\.\d+)?px\]/g

/* ── ALLOWLIST 3 · the design debt registers ──────────────────────────────────
   `lib/design/` is where this system keeps its own registers of hand-rolled
   typography — `eyebrow-exceptions.ts` names each offending file and quotes the
   class it spells out, in a `reason:` string, so the entry can be read without
   opening the file it describes.

   Those quotes are DATA, not comments, so the stripper cannot reach them, and a
   rule that fires on the register documenting the same defect gets answered by
   deleting the documentation — the exact failure docs/28 hit when the first hex
   pass flagged brand-theme.ts's own annotations. Named as a directory, so the
   exception is visible in the file tree rather than hidden in a list. */
const TYPE_SIZE_EXEMPT = /^lib\/design\//

/** 3, 4, 6 or 8 digit hex, as a colour — not a hash-route or an id. */
const HEX = /#[0-9a-fA-F]{3,8}\b/g
/** Tailwind arbitrary SPACING: padding, margin, gap, space, inset — px literals. */
const SPACING =
  /\b(?:-?(?:p|m)[trblxy]?|gap(?:-[xy])?|space-[xy]|inset(?:-[xy])?)-\[[^\]]*\d(?:px|rem)[^\]]*\]/g

for (const file of files) {
  const rel = relative(SCOPE, file)
  const raw = readFileSync(file, 'utf8')
  const code = stripComments(raw)
  const lines = code.split('\n')

  const hexExempt = HEX_EXEMPT_FILES.includes(rel) || BRAND_MARK_PATHS.some((re) => re.test(rel))

  lines.forEach((line, i) => {
    // A hex inside a MASK is not a colour. `mask-image` and its -webkit- alias
    // read the ALPHA channel and discard the colour channel entirely, so
    // `#000` there means "opaque", not "black" — no token could express it
    // better and no colour defect can hide behind this, because a colour
    // written here has no colour effect at all. Narrower than a file
    // exemption on purpose: globals.css is exactly where a real raw hex would
    // do the most damage, so the rest of the file stays enforced.
    const isMaskStop = /(?:^|[;{\s])-?(?:webkit-)?mask(?:-image)?\s*:/.test(line)
    if (!hexExempt && !isMaskStop) {
      for (const m of line.matchAll(HEX)) violations.hex.push({ rel, line: i + 1, text: m[0] })
    }
    for (const m of line.matchAll(SPACING)) {
      violations.spacing.push({ rel, line: i + 1, text: m[0] })
    }
    if (!TYPE_SIZE_EXEMPT.test(rel)) {
      for (const m of line.matchAll(FONT_SIZE)) {
        violations.typesize.push({
          rel,
          line: i + 1,
          text: `${m[0]} — use a type-* step (docs/26 §5)`,
        })
      }
    }
    for (const m of line.matchAll(BREAKPOINT_LIKE)) {
      if (DEFINED_BREAKPOINTS.has(m[2])) continue
      violations.breakpoint.push({
        rel,
        line: i + 1,
        text: `${m[1] ? `${m[1]}-` : ''}${m[2]}: is not a breakpoint here (have: ${[...DEFINED_BREAKPOINTS].join(', ')})`,
      })
    }
  })

  /* Rule 3 · a <button> that is BOTH disabled and labelled coming-soon.
     Matched over the whole element rather than one line, because the attribute
     and the label are almost never on the same line in formatted JSX. */
  for (const m of code.matchAll(/<button\b[\s\S]{0,600}?<\/button>/g)) {
    const el = m[0]
    if (/\bdisabled\b/.test(el) && /coming\s*soon/i.test(el)) {
      violations.disabled.push({
        rel,
        line: code.slice(0, m.index).split('\n').length,
        text: 'disabled <button> labelled coming soon',
      })
    }
  }
}

/* ── THE SPACING RATCHET ──────────────────────────────────────────────────────
   MEASURED when this rule was written: 133 hardcoded spacing values across
   seven lanes' files. Two honest options and one dishonest one.

   Dishonest: drop the rule, or scope it to the files this lane happens to
   touch. Then the leg still cannot fail for anyone else, which is the exact
   defect being fixed.

   Rejected: fix all 133 now. Most sit in routes other lanes own — /approvals,
   /admin, /campaigns, /brain — and rewriting another lane's spacing to satisfy
   a rule they have not read is how a merge conflict becomes a regression.

   Chosen: a RATCHET, with the debt written down in `design-lint-baseline.json`
   rather than hidden in an ignore list. Per FILE counts, not per line: line
   numbers churn on every edit, so a line-keyed baseline goes stale immediately
   and stops being read. A file may never gain a violation, and every one it
   loses tightens the baseline permanently. The number is in the file, in git,
   and it only goes down.

   Regenerate with --update-baseline after REMOVING violations. It refuses to
   loosen: a file that gained violations is reported, never absorbed. */
const BASELINE_PATH = join(ROOT, 'scripts/design/design-lint-baseline.json')

function loadBaseline(key) {
  try {
    return JSON.parse(readFileSync(BASELINE_PATH, 'utf8'))[key] ?? {}
  } catch {
    return {}
  }
}

function countByFile(list) {
  const out = {}
  for (const v of list) out[v.rel] = (out[v.rel] ?? 0) + 1
  return out
}

let failed = 0

/* Rules 1 and 3 are at ZERO and are enforced strictly — no baseline, no grace.
   Measured at zero when written, so any violation is one this lane or a later
   one introduced. */
for (const [key, name, why] of [
  ['hex', 'raw hex colour', 'docs/26 §11 — tokens only'],
  ['disabled', 'disabled coming-soon button', 'docs/26 §10.2 — use a <span>'],
]) {
  const found = violations[key]
  if (found.length === 0) {
    console.log(`  ok    ${name}`)
    continue
  }
  failed += found.length
  console.log(`  FAIL  ${name} — ${found.length} (${why})`)
  for (const v of REPORT ? found : found.slice(0, 12)) {
    console.log(`          ${v.rel}:${v.line}  ${v.text}`)
  }
  if (!REPORT && found.length > 12) console.log(`          … ${found.length - 12} more (--report)`)
}

/* Rules 2 and 4 · ratcheted, same mechanism.
   Rule 4's eight hits were all REAL. Three sat in files this lane owns and are
   fixed. The other five are in /admin and /onboarding, and "fixing" a dead
   class there is not a no-op — it turns a one-column layout into two at 700px,
   on a screen this lane has neither seen nor shot. That is a visual change to
   another lane's work, so it is written down instead. */
const RATCHETED = [
  ['spacing', 'hardcoded spacing', 'docs/26 §6 — use --space-N / the 4pt scale'],
  ['breakpoint', 'dead breakpoint variant', 'globals.css defines narrow/wide only'],
  /* Rule 5 is ratcheted for the reason rule 2 is, only more so: its 847 hits
     span 192 files across every lane running right now. Rewriting another
     lane's type to satisfy a rule they have not read turns a merge into a
     regression, and type is not spacing — moving a call site onto a step
     CHANGES ITS RENDERED SIZE when the old value was off-scale, which is a
     visual change to a screen this lane has neither seen nor shot. Written
     down, and it only goes down. */
  ['typesize', 'hand-written font size', 'docs/26 §5/§11 — use a type-* step'],
]

if (process.argv.includes('--update-baseline')) {
  /* ── THE REFUSAL THIS BLOCK CLAIMED TO HAVE AND DID NOT ─────────────────────
     The comment above BASELINE_PATH has always said "It refuses to loosen: a
     file that gained violations is reported, never absorbed." It did not. The
     old body rewrote the register from the CURRENT counts unconditionally, so
     `--update-baseline` silently absorbed every regression it was documented to
     block — a guard that could never fire, in the one command whose whole job
     is to not be used that way. Found while integrating eleven lanes, where
     running it would have absorbed 28 violations and a real regression together
     and reported success.

     Two DIFFERENT things are now distinguished, because they are different:

       · a BASELINED file that got WORSE — always refused. This is the ratchet.
       · a file the register has never SEEN — refused too, unless `--absorb-new`
         is passed. That is the integration case: code written on a lane the
         rule had not reached yet. It is still debt, so it must be recorded
         deliberately, named on stdout, and visible as a JSON diff in git —
         never as a side effect of "the gate was red so I re-baselined". */
  const absorbNew = process.argv.includes('--absorb-new')
  const refusals = []
  const absorbing = []
  for (const [key, name] of RATCHETED) {
    const baseline = loadBaseline(key)
    for (const [rel, n] of Object.entries(countByFile(violations[key]))) {
      if (rel in baseline) {
        if (n > baseline[rel]) refusals.push(`  REFUSED  ${name}: ${rel} ${baseline[rel]} -> ${n}`)
      } else if (!absorbNew) {
        refusals.push(
          `  REFUSED  ${name}: ${rel} is new to the register with ${n} (need --absorb-new)`,
        )
      } else {
        absorbing.push(`  absorbing  ${name}: ${rel}  ${n}`)
      }
    }
  }
  if (refusals.length > 0) {
    console.log('  baseline NOT written — the register only goes down:')
    for (const r of refusals) console.log(r)
    process.exit(1)
  }
  for (const a of absorbing) console.log(a)
  const out = {
    _: 'Debt register for the ratcheted rules. Counts may only go DOWN — see design-lint.mjs.',
  }
  for (const [key] of RATCHETED) {
    const counts = countByFile(violations[key])
    out[`${key}_total`] = violations[key].length
    out[key] = Object.fromEntries(
      Object.keys(counts)
        .sort()
        .map((r) => [r, counts[r]]),
    )
  }
  writeFileSync(BASELINE_PATH, `${JSON.stringify(out, null, 2)}\n`)
  for (const [key, name] of RATCHETED) {
    console.log(`  baseline written — ${violations[key].length} ${name}`)
  }
} else
  for (const [key, name, why] of RATCHETED) {
    const current = countByFile(violations[key])
    const baseline = loadBaseline(key)
    const regressed = []
    for (const [rel, n] of Object.entries(current)) {
      const allowed = baseline[rel] ?? 0
      if (n > allowed) regressed.push({ rel, n, allowed })
    }
    const improved = Object.entries(baseline).filter(([rel, n]) => (current[rel] ?? 0) < n)
    const total = violations[key].length
    const baseTotal = Object.values(baseline).reduce((a, b) => a + b, 0)

    if (regressed.length === 0) {
      console.log(`  ok    ${name} — ${total} known, none new (baseline ${baseTotal})`)
      if (improved.length > 0) {
        console.log(
          `        ${improved.length} file(s) improved — run --update-baseline to tighten it`,
        )
      }
    } else {
      failed += regressed.length
      console.log(`  FAIL  ${name} — NEW in ${regressed.length} file(s)`)
      console.log(`        ${why}`)
      for (const r of regressed) {
        console.log(`          ${r.rel}  ${r.n} (baseline allows ${r.allowed})`)
        for (const v of violations[key].filter((v) => v.rel === r.rel)) {
          console.log(`            :${v.line}  ${v.text}`)
        }
      }
    }
  }

console.log(`\n  ${files.length} files scanned in apps/web/src`)
process.exit(failed > 0 ? 1 : 0)
