import { Buffer } from 'node:buffer'
import { deflateSync } from 'node:zlib'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { Page } from '@playwright/test'

import { adminClient, expect, signInSecondContext, test } from './fixtures/seeded-user'
import { leaveOnboarding } from './fixtures/compose'
import { framesTaken, shot, timedGoto, useTheme, type Theme } from './helpers/ux-shot'

/**
 * JOURNEY 4 — THE PERSON WHO MAKES A MISTAKE.
 *
 * Every screen in this file is one a person reaches by being wrong. That is the
 * half of a product nobody photographs, and the half a shop owner meets on their
 * first bad afternoon.
 *
 * The question at each stop is the same and it is not "did it refuse". It is:
 * **does the screen say what would work?** A refusal with no remedy is a dead
 * end wearing the clothes of a validation message.
 *
 * Six mistakes, each its own test so one dead end cannot hide the next:
 *   A  over the character limit
 *   B  a picture the channel will not take
 *   C  no credits, mid-action
 *   D  two tabs, and the second one is stale
 *   E  leaving with unsaved words on the screen
 *   F  a URL that does not exist, and one that belongs to someone else
 */

const JOURNEY = 'j4-mistakes'

/**
 * EVERY test in this file must capture something.
 *
 * These specs assert almost nothing on purpose — their product is frames, and a
 * dead end is a finding rather than a failure. That trade has one hole in it: a
 * run whose sign-in silently parked on /sign-in, or whose selectors all missed,
 * writes zero PNGs and reports green. This closes it in one place rather than
 * thirteen, and it is the difference between "nothing broke" and "nothing ran".
 */
let framesAtStart = 0
test.beforeEach(() => {
  framesAtStart = framesTaken()
})
test.afterEach(() => {
  expect(framesTaken()).toBeGreaterThan(framesAtStart)
})

async function bootstrap(page: Page): Promise<void> {
  await page.goto('/home')
  const create = page.locator('#main').getByRole('button', { name: /create workspace/i })
  try {
    await create.waitFor({ state: 'visible', timeout: 10_000 })
    await create.click()
    await page.waitForURL(/\/onboarding/, { timeout: 30_000 })
    await leaveOnboarding(page)
  } catch {
    /* already bootstrapped */
  }
}

/** Open the composer on a real row for one channel, and return the post id. */
async function composerOn(page: Page, channel: string): Promise<string | null> {
  await timedGoto(page, '/posts/new')
  const tile = page.locator(`[data-channel-tile="${channel}"]`)
  try {
    await tile.waitFor({ state: 'visible', timeout: 10_000 })
    await tile.click()
    await page.waitForURL(/\/posts\/[0-9a-f-]{36}$/, { timeout: 60_000 })
  } catch {
    return null
  }
  return new URL(page.url()).pathname.split('/').pop() ?? null
}

/**
 * A real PNG, at a deliberately illegal shape.
 *
 * Hand-encoded rather than generated by a library: `sharp` is only a transitive
 * dependency here and adding one for eight bytes of pixel data would rewrite the
 * lockfile. The CRC is computed properly, so this is a file a decoder accepts —
 * the refusal under test has to be about the SHAPE, not about a corrupt upload.
 */
function pngOf(width: number, height: number): Buffer {
  const crcTable: number[] = []
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    crcTable[n] = c >>> 0
  }
  const crc = (buf: Buffer): number => {
    let c = 0xffffffff
    for (const b of buf) c = crcTable[(c ^ b) & 0xff]! ^ (c >>> 8)
    return (c ^ 0xffffffff) >>> 0
  }
  const chunk = (type: string, body: Buffer): Buffer => {
    const len = Buffer.alloc(4)
    len.writeUInt32BE(body.length)
    const typed = Buffer.concat([Buffer.from(type, 'ascii'), body])
    const c = Buffer.alloc(4)
    c.writeUInt32BE(crc(typed))
    return Buffer.concat([len, typed, c])
  }
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(width, 0)
  ihdr.writeUInt32BE(height, 4)
  ihdr.writeUInt8(8, 8) // bit depth
  ihdr.writeUInt8(2, 9) // truecolour
  // One filter byte plus three bytes per pixel, per row. Solid mid-grey.
  const raw = Buffer.concat(
    Array.from({ length: height }, () =>
      Buffer.concat([Buffer.from([0]), Buffer.alloc(width * 3, 0x88)]),
    ),
  )
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

/**
 * 1024 is in this list and it is not padding.
 *
 * The app has exactly two breakpoints, 700 and 1180 (docs/26 §9.1), so 390 and
 * 1440 both land in terminal bands and NEITHER visits 700-1179. Past audits
 * found their best defects there — a row pushing the page to 464px, a caption
 * floating 178px from the box it names — and an ERROR screen is precisely where
 * a constrained layout gives way, because it is the layout carrying an extra
 * sentence nobody budgeted for.
 *
 * Light only at 1024: the dark-specific defects in this file (the AI-disclosure
 * checkbox, the file pill) are theme defects rather than width defects, and they
 * are already covered at both terminal widths.
 */
const COMBOS: { width: number; theme: Theme }[] = [
  { width: 1440, theme: 'light' },
  { width: 1024, theme: 'light' },
  { width: 390, theme: 'light' },
  { width: 1440, theme: 'dark' },
  { width: 390, theme: 'dark' },
]

for (const { width, theme } of COMBOS) {
  test.describe(`ux j4 mistakes ${width} ${theme}`, () => {
    test(`A over the character limit ${width} ${theme}`, async ({ page, signedIn }) => {
      void signedIn
      test.setTimeout(200_000)
      await page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
      await useTheme(page, theme)
      await bootstrap(page)

      // X is the tightest limit in the product, so it is where the refusal shows
      // first and where an unhelpful one costs the most.
      const id = await composerOn(page, 'x')
      const body = page.getByLabel('Your post')
      if (!(await body.isVisible().catch(() => false))) {
        await shot(page, {
          journey: JOURNEY,
          stop: 'A1-no-composer',
          width,
          theme,
          note: `composerOn('x') returned ${id}`,
        })
        return
      }
      await body.fill(
        'We roast every Tuesday and we sell only what we roasted that week, which sounds like a slogan until you taste the difference between a bag opened on Thursday and the same bag opened three weeks later, and once you have tasted that you will never go back to a supermarket shelf again, so come in on Saturday morning and we will pour you both side by side and say nothing at all while you decide which one you actually want to take home with you today.',
      )
      await page.waitForTimeout(2500)
      await shot(page, { journey: JOURNEY, stop: 'A2-over-limit', width, theme })

      // Now ask it to go out anyway. What the product says HERE is the whole test.
      const commit = page.getByRole('button', { name: /schedule|publish|send|approve/i }).first()
      if (await commit.isVisible().catch(() => false)) {
        await commit.click().catch(() => {})
        await page.waitForTimeout(2000)
      }
      await shot(page, { journey: JOURNEY, stop: 'A3-over-limit-commit', width, theme })
    })

    test(`B a picture the channel will not take ${width} ${theme}`, async ({ page, signedIn }) => {
      void signedIn
      test.setTimeout(200_000)
      await page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
      await useTheme(page, theme)
      await bootstrap(page)
      await composerOn(page, 'instagram')

      // 1200x300 is 4:1 — far outside Instagram's floor, and a shape a person
      // genuinely arrives with (a website banner).
      const input = page.locator('input[type="file"]').first()
      if (await input.count()) {
        await input
          .setInputFiles({ name: 'banner.png', mimeType: 'image/png', buffer: pngOf(1200, 300) })
          .catch(() => {})
        await page.waitForTimeout(4000)
        await shot(page, { journey: JOURNEY, stop: 'B1-wrong-aspect', width, theme })
      } else {
        await shot(page, {
          journey: JOURNEY,
          stop: 'B1-wrong-aspect',
          width,
          theme,
          note: 'no file input on the composer — a picture cannot be attached here at all',
        })
      }

      // And the assets library, which is the other door the same file arrives by.
      await timedGoto(page, '/assets')
      await shot(page, { journey: JOURNEY, stop: 'B2-assets', width, theme })
    })

    test(`C no credits, mid-action ${width} ${theme}`, async ({ page, signedIn }) => {
      test.setTimeout(200_000)
      await page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
      await useTheme(page, theme)
      await bootstrap(page)

      // Spend the whole signup grant through THE sanctioned write path. Never a
      // raw UPDATE on credit_balances: that table has exactly one legal writer
      // and a test that bypasses it is testing a state the app cannot produce.
      const admin = adminClient()
      let zeroed = false
      if (admin) {
        const { data } = await admin
          .from('workspaces')
          .select('id')
          .eq('created_by', signedIn.clerkUserId)
          .limit(1)
        const workspaceId = data?.[0]?.id
        if (workspaceId) {
          // `pg` is a dependency of packages/billing, not of apps/web, and
          // adding one here to zero a test balance would rewrite the lockfile.
          // Resolved from the package that legitimately owns it instead.
          const requireFromBilling = createRequire(
            join(
              dirname(fileURLToPath(import.meta.url)),
              '..',
              '..',
              '..',
              'packages',
              'billing',
              'index.js',
            ),
          )
          const { Client } = requireFromBilling('pg') as {
            Client: new (config: { connectionString: string }) => {
              connect(): Promise<void>
              query(text: string, values: unknown[]): Promise<unknown>
              end(): Promise<void>
            }
          }
          const url = process.env.SUPABASE_DB_URL
          if (url) {
            const client = new Client({ connectionString: url })
            try {
              await client.connect()
              await client.query(
                `select app.apply_ledger_entry($1::uuid, 'DEBIT', $2::int, $3::text, $4::text)`,
                [workspaceId, 100, `ux-zero-${workspaceId}`, 'ux_probe'],
              )
              zeroed = true
            } catch {
              /* recorded below as a note rather than swallowed */
            } finally {
              await client.end().catch(() => {})
            }
          }
        }
      }

      const note = zeroed ? undefined : 'BALANCE NOT ZEROED — this frame is a 100-credit workspace'
      await timedGoto(page, '/wallet')
      await shot(page, { journey: JOURNEY, stop: 'C1-wallet-empty', width, theme, note })
      await timedGoto(page, '/home')
      await shot(page, { journey: JOURNEY, stop: 'C2-home-no-credits', width, theme, note })

      // The paid action, pressed with nothing to pay with.
      const plan = page.getByRole('button', { name: /plan my week/i }).first()
      if (await plan.isVisible().catch(() => false)) {
        await plan.click().catch(() => {})
        await page.waitForTimeout(4000)
      }
      await shot(page, { journey: JOURNEY, stop: 'C3-paid-action-refused', width, theme, note })

      await timedGoto(page, '/settings/plan')
      await shot(page, { journey: JOURNEY, stop: 'C4-plan', width, theme, note })
    })

    test(`D two tabs, and the second one is stale ${width} ${theme}`, async ({
      page,
      browser,
      signedIn,
    }) => {
      test.setTimeout(240_000)
      await page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
      await useTheme(page, theme)
      await bootstrap(page)
      const id = await composerOn(page, 'instagram')
      if (!id) {
        await shot(page, { journey: JOURNEY, stop: 'D0-no-post', width, theme })
        return
      }
      const body = page.getByLabel('Your post')
      await body.fill('First tab wrote this.').catch(() => {})
      await page.waitForTimeout(2500)

      // A SECOND CONTEXT, not a second tab: two tabs share a cookie jar and a
      // storage state, so a defect that only appears when two SESSIONS disagree
      // about one row would be masked.
      const other = await signInSecondContext(browser, signedIn)
      await other.setViewportSize({ width, height: width === 390 ? 844 : 900 })
      await useTheme(other, theme)
      await other.goto(`/posts/${id}`)
      await other.waitForTimeout(2500)

      // Tab one moves the row forward. Tab two is now holding a version that no
      // longer exists.
      await body.fill('First tab wrote this, then changed its mind.').catch(() => {})
      await page.waitForTimeout(2500)

      const otherBody = other.getByLabel('Your post')
      await otherBody.fill('Second tab never saw any of that.').catch(() => {})
      await other.waitForTimeout(3500)
      await shot(other, { journey: JOURNEY, stop: 'D1-stale-save', width, theme })
      await other.context().close()
    })

    test(`E leaving with unsaved words on the screen ${width} ${theme}`, async ({
      page,
      signedIn,
    }) => {
      void signedIn
      test.setTimeout(200_000)
      await page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
      await useTheme(page, theme)
      await bootstrap(page)
      await composerOn(page, 'instagram')
      const body = page.getByLabel('Your post')
      if (await body.isVisible().catch(() => false)) {
        // Type and leave IMMEDIATELY, inside any debounce.
        await body.fill('Words that were never saved anywhere.')
        await page.waitForTimeout(150)
      }
      const home = page.getByRole('link', { name: /^home$/i }).first()
      if (await home.isVisible().catch(() => false)) {
        await home.click().catch(() => {})
      } else {
        await page.goto('/home')
      }
      await page.waitForTimeout(2500)
      await shot(page, { journey: JOURNEY, stop: 'E1-left-mid-edit', width, theme })

      await timedGoto(page, '/posts')
      await shot(page, { journey: JOURNEY, stop: 'E2-did-it-survive', width, theme })
    })

    test(`F a URL that is wrong ${width} ${theme}`, async ({ page, signedIn }) => {
      void signedIn
      test.setTimeout(200_000)
      await page.setViewportSize({ width, height: width === 390 ? 844 : 900 })
      await useTheme(page, theme)
      await bootstrap(page)

      await timedGoto(page, '/this-route-does-not-exist')
      await shot(page, { journey: JOURNEY, stop: 'F1-not-found', width, theme })

      // A well-formed id for a post in SOMEBODY ELSE'S workspace. RLS answers
      // nothing; the question is what the SCREEN then says.
      await timedGoto(page, '/posts/00000000-0000-4000-8000-000000000000')
      await shot(page, { journey: JOURNEY, stop: 'F2-someone-elses-post', width, theme })

      await timedGoto(page, '/campaigns/00000000-0000-4000-8000-000000000000')
      await shot(page, { journey: JOURNEY, stop: 'F3-someone-elses-campaign', width, theme })
    })
  })
}
